### ISSUE TITLE
Maybe use Pipenv instead of a requirements.txt?

### ISSUE THREAD

**Issue by bowbahdoe** [intuit/foremast-brain#5]
A requirements.txt cannot track versions of transitive dependencies without explicit freezing which makes for the possibility of dependency drift and unpredictible builds. It also leaves it up to each developer to use virtualenvs, which can make for a "it works on my machine" type scenario to occur with specific dependency versions.

The current officially recommended packaging tool from Python.org is Pipenv and it manages quite a few of these issues with lockfiles and automatic virtual environments. It can also generate a requirements.txt on the fly to fit in with existing build pipelines. I think it is something worth considering, although it isn't pressing until a transitive dependency breaks on an update and causes an issue.

[This is a talk from the most recent pycon about the tool](https://www.youtube.com/watch?v=GBQAKldqgZs), which might answer more questions than I can off the top of my head.

**Comment by pzou1974** [comment]
Here is what I found https://tech.instacart.com/freezing-pythons-dependency-hell-in-2018-f1076d625241

**Comment by bowbahdoe** [comment]
I will look into it in a bit. My first impression of Lore is that is a product of NIH, but I will do more research.

**Comment by pzou1974** [comment]
sounds great!  Thank you

**Comment by ParticularlyPythonicBS** [comment]
I can take this if no one else is working on it. First-time contributor
