### ISSUE TITLE
Make master-dev branch has all the dev and master features

### ISSUE THREAD

**Issue by pzou1974** [intuit/foremast-brain#56]
Tag existing master branch and merge dev to master

**Comment by rohan8594** [comment]
You mean merge master to dev? Because your master is currently ahead of dev. Or am I missing something?

**Comment by man007yadav** [comment]
Can i take this one up?

**Comment by janitha09** [comment]
git checkout master
git tag -a v1.0 -m "version 1.0"
git merge origin/dev
git push

**Comment by pzou1974** [comment]
I will approve your issue.  Thank you for your help.  I approve your contribution.  you can close this issue.  Suggest create dev-master branch and push all the change there.
